Integrate Get Coins API
zhenyapavlovsky/crypto_app_ios pull request #16
Opened 2023-03-27 16:19 UTC by zhenyapavlovsky

## What's new
1.  Integrated Get Coins API

## Issue

[Issue](https://trello.com/c/jAQmcx3C)

## Video

https://user-images.githubusercontent.com/99541081/227999623-5c51f4d8-4fd9-4841-8f55-459cdbd6f345.mov

2023-03-27 16:54 UTC, vasylnadtochii requested changes

2023-03-27 16:54 UTC, vasylnadtochii commented on Crypto_App_iOS/Flows/Coordination/MainCoordinator/MainCoordinator.swift
> +    func routeToDetailView(coins: Coins.Coin) {
```suggestion
    func routeToDetailView(coin: Coins.Coin) {
```

2023-03-27 16:54 UTC, vasylnadtochii commented on Crypto_App_iOS/Flows/Screens/Detail/DetailViewModel.swift
> +    var coins: Coins.Coin
```suggestion
    var coin: Coins.Coin
```

2023-03-27 16:54 UTC, vasylnadtochii commented on Crypto_App_iOS/Flows/Screens/Detail/DetailViewModel.swift
> +        UIApplication.shared.open(url)
please create separate `URLManager` and move this code inside it

2023-03-27 16:54 UTC, vasylnadtochii commented on Crypto_App_iOS/Flows/Screens/Detail/DetailView.swift
> +//struct DetailView_Previews: PreviewProvider {
why is this commented down?

2023-03-27 16:54 UTC, vasylnadtochii commented on Crypto_App_iOS/Flows/Screens/Detail/DetailLoadingView.swift
> +//struct DetailLoadingView_Previews: PreviewProvider {
why is it commented down?

2023-03-27 16:54 UTC, vasylnadtochii commented on Crypto_App_iOS/Flows/Screens/Home/HomeView.swift
> +    @ObservedObject var viewModel = HomeViewModelImpl(
it should be injected

2023-03-27 16:54 UTC, vasylnadtochii commented on Crypto_App_iOS/Flows/Screens/Home/HomeView.swift
> +            .onAppear() {
```suggestion
            .onAppear(viewModel.getCoins)
```

2023-03-27 16:54 UTC, vasylnadtochii commented on Crypto_App_iOS/Flows/Screens/Home/HomeView.swift
> +    func createButton(coins: Coins.Coin, action: (() -> Void)?) -> some View {
```suggestion
    func createButton(coin: Coins.Coin, action: (() -> Void)?) -> some View {
```

2023-03-27 16:54 UTC, vasylnadtochii commented on Crypto_App_iOS/Flows/Screens/Home/HomeView.swift
> +                )
bad alignment

2023-03-27 16:54 UTC, vasylnadtochii commented on Crypto_App_iOS/Flows/Screens/Home/HomeViewModel.swift
> +    @Published var loading = false
please use loading state instead

2023-03-27 16:54 UTC, vasylnadtochii commented on Crypto_App_iOS/Flows/Screens/Home/HomeViewModel.swift
> +    @Published var output = String()
remove this and use `LoadingState`

2023-03-27 16:54 UTC, vasylnadtochii commented on Crypto_App_iOS/Services/ServiceContainer.swift
>      lazy var userService = UserServiceImpl(executor: NetworkRequestExecutor())
what does `userService` stand for? 
If it is not needed, then remove it

2023-03-27 17:31 UTC, zhenyapavlovsky commented on Crypto_App_iOS/Flows/Coordination/DetailCoordinator/DetailCoordinatorView.swift
> +            //    DetailView(viewModel: coordinator.detailViewModel)
Done

2023-03-27 18:42 UTC, zhenyapavlovsky commented on Crypto_App_iOS/Flows/Coordination/MainCoordinator/MainCoordinator.swift
> +    func routeToDetailView(coins: Coins.Coin) {
Done

2023-03-27 18:53 UTC, zhenyapavlovsky commented on Crypto_App_iOS/Flows/Screens/Detail/DetailViewModel.swift
> +        UIApplication.shared.open(url)
Done

2023-03-27 18:57 UTC, zhenyapavlovsky commented on Crypto_App_iOS/Flows/Screens/Home/HomeView.swift
> +            .onAppear() {
Done

2023-03-27 19:10 UTC, zhenyapavlovsky commented on Crypto_App_iOS/Services/ServiceContainer.swift
>      lazy var userService = UserServiceImpl(executor: NetworkRequestExecutor())
Done

2023-03-28 09:58 UTC, zhenyapavlovsky commented on Crypto_App_iOS/Flows/Screens/Detail/DetailViewModel.swift
> +    var coins: Coins.Coin
Done

2023-03-28 09:59 UTC, zhenyapavlovsky commented on Crypto_App_iOS/Flows/Screens/Detail/DetailViewModel.swift
> +    init(coins: Coins.Coin, coinService: CoinService) {
Done

2023-03-28 10:00 UTC, zhenyapavlovsky commented on Crypto_App_iOS/Flows/Screens/Home/HomeView.swift
> +            .onAppear() {
Done

2023-03-28 10:01 UTC, zhenyapavlovsky commented on Crypto_App_iOS/Flows/Screens/Home/HomeView.swift
> +    func createButton(coins: Coins.Coin, action: (() -> Void)?) -> some View {
Done

2023-03-28 10:09 UTC, zhenyapavlovsky commented on Crypto_App_iOS/Flows/Screens/Home/HomeView.swift
> +                )
Done

2023-03-28 10:10 UTC, zhenyapavlovsky commented on Crypto_App_iOS/Flows/Screens/Home/HomeViewModel.swift
> +    @Published var loading = false
Done

2023-03-28 10:10 UTC, zhenyapavlovsky commented on Crypto_App_iOS/Flows/Screens/Home/HomeViewModel.swift
> +    @Published var output = String()
Done

2023-03-28 10:11 UTC, zhenyapavlovsky commented on Crypto_App_iOS/Services/ServiceContainer.swift
>      lazy var userService = UserServiceImpl(executor: NetworkRequestExecutor())
Done

2023-03-28 10:17 UTC, zhenyapavlovsky commented on Crypto_App_iOS/Flows/Screens/Detail/DetailView.swift
> +//struct DetailView_Previews: PreviewProvider {
Done

2023-03-28 10:18 UTC, zhenyapavlovsky commented on Crypto_App_iOS/Flows/Screens/Detail/DetailLoadingView.swift
> +//struct DetailLoadingView_Previews: PreviewProvider {
Done

2023-03-28 10:31 UTC, zhenyapavlovsky commented on Crypto_App_iOS/Flows/Coordination/MainCoordinator/MainCoordinator.swift
> +    init(homeViewModel: HomeViewModelImpl) {
Done

2023-03-28 10:33 UTC, zhenyapavlovsky commented on Crypto_App_iOS/Flows/Screens/Home/HomeView.swift
> +    @ObservedObject var viewModel = HomeViewModelImpl(
Done

2023-03-29 10:52 UTC, vasyl-nadtochii approved these changes

2023-03-29 10:52 UTC, vasyl-nadtochii commented on Crypto_App_iOS/Flows/Screens/Home/HomeView.swift
> +        HomeView(viewModel: HomeViewModelImpl(
move `viewModel: HomeViewModelImpl(` to next line and format whole block of code appropriately

2023-03-29 12:30 UTC, zhenyapavlovsky commented on Crypto_App_iOS/Flows/Screens/Home/HomeView.swift
> +        HomeView(viewModel: HomeViewModelImpl(
Done

2023-03-29 12:30 UTC, merged